[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/astaxie/beego"
  version = "1.9.2"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.3.0"

[[constraint]]
  name = "github.com/graphql-go/graphql"
  version = "0.7.5"

[[constraint]]
  name = "github.com/kr/pretty"
  version = "0.1.0"
